### ISSUE TITLE
Write tests for the Row and Column components.

### ISSUE THREAD

**Issue by rabingaire** [rabingaire/react-grid#1]

**Comment by Velveeta** [comment]
I can jump on this one. Looks like you'll need the testing infrastructure set up also. Do you have a preference on which test library you want to go with?

**Comment by rabingaire** [comment]
Use Jest I am fine with it :+1: Thank You very much :)

**Comment by Velveeta** [comment]
Perfect, I'll get on it :)

**Comment by Velveeta** [comment]
Just checking back in here. I'd intended to get this done during some time we'd carved out specifically for this sort of thing at work yesterday, but then kept getting sidetracked with actual work items, and today is going to be pretty busy for me during the work day. This is nearly done, though, I'll try to get it pushed sometime tonight, so you're not sitting in limbo about it :)

**Comment by rabingaire** [comment]
I am happy that you are working on this. Thank you very much :) I can wait for a while :)
